* Meaning of Ideology

** Ability to recruit people to fight for you
*** It could be moral: if we win, this is best for everyone
*** It could be entirely selfish: if you fight for us, you will be paid

** Ability to disarm people, i.e. prevent them from opposing you

** There is no need for ideology to be very popular, it only needs to be the most popular choice among the available, or even least hated.
*** Example of least hated: Bolsheviks
*** Bolsheviks were able to forcefully mobilize people to fight for them, many of these people did not want to fight for Bolsheviks, but there was no other force they could join and if they were to refuse to fight, they would be shot.
*** This shows that even with a little violent power you can multiply it, as long as the enemy cannot offer a worthy cause to fight for.
*** Russia vs Ukraine, neither country can offer the citizens compelling case to fight for in the war?

*** Modern dictatorships clear out the choice, so even though the do not present a compelling choice, people still do not oppose them as there is nothing to rally behind to oppose them

* Instead of ideology people could rally  behind a specific person as an avatar of competence/greatness/(also ideology)/national pride
** Napoleon
** Ceasar
** Lenin
** Definitely no Kerensky



* Disbalance between political/administrative power and the ability to mobilze violent power tends to correct itself over time

** If there is an entity capable of more violence than the current political ruling entity, then it takes over the country: coup de ta or revolution.
** In the event, it is difficult to disarm their opponents, the regimes tend to arm themselves better.
*** For example, as the regime becomes less popular among general populace, its ability to prevent people from considering violent action against the administrative power declines, hence the regime increases its own capacity for violence via recruting more police/army/intelligence.
** If either of the option fails, usually due to incompetence of the adminstration or the infighting in the ruling class, then there is one option to maintain the administration in power: agree to limited concessions that are enough to disarm the opposition to a sufficient degree. By giving concessions, they give people enough of what they want so the calculus of risk vs reward becomes skewed towards accepting the deal for most people. This is an example of using ideologies/words for modifying the capacity for violence of the opponent.
*** Once enough has been offered to appease the moderates, the administration may join forces with moderates to crush those in the opposition who want more and still want to fight. Once opposition is crushed, administration typically is free to roll back at least some of the concessions they were forced to offer.
*** Observable failure of the administration in the revolutions is offering too little too late. Often times if they offer concessions more promptly or more concessions, they would appease moderates enough to exit the fight.

** As a corollary to this, the administrative powers tend to persecute or limit any entities that attempt to increase their ability to exhert violence.
*** This tends to be the primary way the modern states manage opposition, this option became widely available thanks to the new technological advances.
*** Modern states are weak, their capacity to mobilize citizens for violence is generally very low, except by force, like Bolsheviks. But, at least on the inside, there is no competing opposition to fight against and any opposition that could mobilize people for violence is taken care off before they get strong.
*** If the trend for increased incompetence of governance to continue, perhaps such opposition will emerge somewhere, this is interesting to observe.
*** Personally I believe that you only need a few competent people to clear out opposition with the modern technologies.
*** Also AI might make this maintenance of power issue even easier.



** Corollary
*** Once the dominance in the violence sphere is estabilished, the ability to push unpopular changes is unlocked.
*** What limites the administration in terms of decision making, is not how much the populace likes the decisions, but rather how much the elites/ruling class/or people with great capacity for violence(#) like the decisions, and how competent are the people who keep the opposition's capacity for violence.
(#)people achieve great capacity of violence by the following means via (1) charisma, inspiring loyalty of arms-bearing individuals or with (2) resources, for example money, buying mercenaries, or (3) administrative control over police, army, intelligence agencies


** It seems, that capacity for violence is rather a measurement of an ability to take political power. The actual source of political power for an individual or organization is the ability to secure the capacity for violence via projection of competence, charisma, compelling ideology, and distribution of resources to the followers who lend their capacity for violence to the given individual or organization.